version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    ports:
      - "54324:5432"
    volumes:
      - postgres_remapp:/data/postgres
      - ./MacDockerSharedData:/mac-data/
    command: postgres -c 'max_connections=1000'

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_remapp:/var/lib/pgadm
      - ./SharedData:/SharedData/
    ports:
      - "5056:80"
    restart: unless-stopped
    depends_on:
      - db
  
volumes:
  postgres_remapp:
  pgadmin_remapp:
